version: '3'
services:
  php:
    build:
      context: .docker
      dockerfile: php.Dockerfile
    container_name: pixel-canvas
    ports:
      - 8666:80
    volumes:
      - ./app:/var/www/html
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .docker/database.env
    volumes:
      - db-data:/var/lib/postgresql/data/:rw
volumes:
  db-data: null
